### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Chowe911** [sin1ght/rss-web#1]
Hi, according to the *readme* at client, I try to run *npm install*, and it is ok. However, when I try to run *npm run serve*, something wrong hapen. This is the log: 

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Unexpected console statement (no-console) at src/main.js:36:5:
  34 | router.beforeEach(async (to, from, next) => {
  35 |     const path = to.path
> 36 |     console.log('path',path)
     |     ^
  37 |     const whiteList = ['/login']
  38 |     if(whiteList.includes(path)){
  39 |         next()

error: Unexpected console statement (no-console) at src/main.js:42:9:
  40 |     }else{
  41 |         const res = await isAuth()
> 42 |         console.log('res',res.data);
     |         ^
  43 |         if(res.data.status){
  44 |             store.user=res.data.data;
  45 |             next()

error: 'options' is defined but never used (no-unused-vars) at src/main.js:54:18                                                                   :
  52 | //添加全局属性
  53 | Vue.use({
> 54 |     install(Vue, options){
     |                  ^
  55 |         Vue.prototype.$http=axios;
  56 |         Vue.prototype.$store=store;
  57 |         Vue.prototype.$moment=moment;

3 errors found.

My PC's environment is Windows 10 WSL Ubuntu 18.04.2 LTS, & firewall is working.

**Comment by sin1ght** [comment]
it's error of eslint means dont't use 'console' function,but it doesn't matter.
i have updated the readme to tell you how to run it. :smile:
